### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by GNiklasch** [jkanner/streamlit-dataview#24]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://gw-quickview.streamlit.app/jkanner/streamlit-dataview/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

---
The above being the canned text created when I click on the "Notify app developer" button on the error-message page displayed instead of the GW Quickview UI. The page also points to https://blog.streamlit.io/common-app-problems-resource-limits/ with troubleshooting advice.
I see that you're using `st.cache()` twice, both times passing both `ttl` and `max_entries`- whereas the above page suggests that one and only one of these should be set. I guess that `max_entries` may be more useful.

Background: (a) This is happening after a prolonged scheduled maintenance of the Streamlit Community Cloud yesterday, which may be playing a role.
(b) Perhaps more importantly, usage patterns of your (eminently useful! Thank you!) app have changed of late. We (a few volunteers of the Gravity Spy project on Zooniverse) have started to use it to look at glitches, rather than at GW events - thus throwing dozens of GPS timestamps at it, and therefore accessing raw GWOSC data from many more points in time than would be of interest to astrophysicists. We've been gaining some insights that we couldn't have gained without your app. :) But we may also have been putting unprecedented load on the application, and on the caching in particular. This is _why_ I think `max_entries` may help to rein in the memory consumption, more than `ttl`.

Thank you!

**Comment by jkanner** [comment]
Hi!  

Thank you for the notification, the suggestion, and the kind words.  I'm glad you like the app!

OK - I'll try removing the TTL option, and see if that helps.  Please let me know if you have problems in the future.  Unfortunately, I don't have a monitor for the app, so I rely on volunteers to let me know when it goes down.  Much appreciated!

**Comment by GNiklasch** [comment]
As of ten minutes ago, I see it up and running again. (Thumbs up!)

**Comment by jkanner** [comment]
@GNiklasch  Great.  Thank you, again!
