### ISSUE TITLE
New gwosc release (which knows about new GWOSC domain name)

### ISSUE THREAD

**Issue by GNiklasch** [jkanner/streamlit-dataview#25]
GWOSC is in the process of moving from `www.gw-openscience.org` to [`gwosc.org`](https://gwosc.org/). This affects data download URLs, too. For the moment, all the old URLs end up being redirected to the corresponding new ones.

The latest release 0.7.1 of the `gwosc` module [knows about this change](https://github.com/gwpy/gwosc/commit/e2e0e49ab60896957269c202b517275cf980d9bb).

Since `gwosc` is a dependency of `GWpy`, updating the latter to current 3.0.4 would also update `gwosc` (unless pinned explicitly).

Thought you might be interested! :)

**Comment by jkanner** [comment]
Good catch!  Thank you.

**Comment by jkanner** [comment]
@GNiklasch  Thank you!  I will try to look at this soon.

**Comment by jkanner** [comment]
Now fixed by PR https://github.com/jkanner/streamlit-dataview/pull/26
