### ISSUE TITLE
Unable to launch 

### ISSUE THREAD

**Issue by mdhorninge** [jkanner/streamlit-dataview#33]
Hello, unfortunately I'm unable to launch this application, when starting it says: error running app. Hopefully you can have a look at it, thank you.

**Comment by jkanner** [comment]
@mdhorninge 
Thank you for letting me know!

This link works for me today:
https://gw-quickview.streamlit.app

Could you try again, and let me know if it is working now?

**Comment by mdhorninge** [comment]
Yes it works again! Thank you.
