### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by seokdaseok** [jkanner/streamlit-dataview#35]
I was using this to view some data earlier, but the next day it suddenly kept displaying "Error running app." I waited a few days to try again, and on different devices, but I'm still unable to run the app.

Would you be willing to take a look at this issue? Thank you so much!

**Comment by jkanner** [comment]
@seokdaseok   Thank you for letting me know!  I restarted the app, and it seems OK for now.  Please let me know if you notice additional problems.
